#Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: o-nika
email: nikakw@gmail.com
description: fragments of a discourse
# this means to ignore newlines until "baseurl:"
baseurl: # the subpath of your site, e.g. /blog
url: "https://nikaroxanne.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nikaroxanne
github_username:  nikaroxanne
imageloc: "assets/images"
permalink: pretty

defaults:
  - scope:
      path: "/assets/images"
    values:
      image: true
  - scope:
      path: "/projects/livingArchive/crypt"
      type: "crypt-archives"
    values:
      layout: "crypt"



collections:
  drawings:
    output: true
  paintings:
    output: true
  compArt:
    output: true

# Build settings
markdown: kramdown
theme: minima
minima:
  skin: solarized-dark
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /blog/:year/:month/:day/:title
# Google services
google_analytics: UA-97632940-1

jekyll-archives:
  enabled:
    - year
    - tags
    - categories
  layout: crypt
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/:tag/:name/'
    category: '/:category/:name/'	
